name: Github Pages Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.20]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        working-directory: ./Digital-Bond
        run: npm install && npm run gh-build && cp docs/index.html 
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: main # The branch the action should deploy to.
          folder: Digital-Bond/docs/index.html # The folder the action should deploy.        
